# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

- hosts: remote
  gather_facts: no
  become: yes
  become_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
